import type { INodeProperties } from 'n8n-workflow';

export const crawlFields: INodeProperties[] = [
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: {
				operation: ['crawl'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['crawl'],
			},
		},
		options: [
			{
				displayName: 'Allow External Links',
				name: 'allowExternalLinks',
				type: 'boolean',
				default: false,
				description: 'Whether to follow links to external domains',
			},
			{
				displayName: 'Allow Subdomains',
				name: 'allowSubdomains',
				type: 'boolean',
				default: false,
				description: 'Whether to follow links to subdomains',
			},
			{
				displayName: 'Delay',
				name: 'delay',
				type: 'number',
				default: 200,
				description: 'Delay in milliseconds between requests',
			},
			{
				displayName: 'Exclude Paths',
				name: 'excludePaths',
				type: 'string',
				default: '',
				placeholder: 'e.g. /admin/.*,/private/.*',
				description: 'Comma-separated regex patterns for paths to exclude',
			},
			{
				displayName: 'Include Paths',
				name: 'includePaths',
				type: 'string',
				default: '',
				placeholder: 'e.g. /blog/.*,/docs/.*',
				description: 'Comma-separated regex patterns for paths to include',
			},
			{
				displayName: 'Max Depth',
				name: 'maxDepth',
				type: 'number',
				default: 5,
				description: 'Maximum link depth to crawl',
			},
			{
				displayName: 'Max Retries',
				name: 'maxRetries',
				type: 'number',
				default: 1,
				description: 'Maximum number of retries per page',
			},
			{
				displayName: 'Scrape Exclude Tags',
				name: 'scrapeExcludeTags',
				type: 'string',
				default: '',
				placeholder: 'e.g. nav,footer,aside',
				description: 'Comma-separated HTML tags to exclude when scraping',
			},
			{
				displayName: 'Scrape Formats',
				name: 'formats',
				type: 'multiOptions',
				options: [
					{ name: 'HTML', value: 'html' },
					{ name: 'Markdown', value: 'markdown' },
					{ name: 'Plain Text', value: 'rawText' },
				],
				default: ['markdown'],
				description: 'The output formats for crawled pages',
			},
			{
				displayName: 'Scrape Headers',
				name: 'scrapeHeaders',
				type: 'json',
				default: '{}',
				placeholder: 'e.g. {"Authorization": "Bearer token"}',
				description: 'Custom HTTP headers to send when scraping pages',
			},
			{
				displayName: 'Scrape Include Tags',
				name: 'scrapeIncludeTags',
				type: 'string',
				default: '',
				placeholder: 'e.g. article,main,section',
				description: 'Comma-separated HTML tags to include when scraping',
			},
			{
				displayName: 'Scrape Only Main Content',
				name: 'scrapeOnlyMainContent',
				type: 'boolean',
				default: true,
				description: 'Whether to extract only the main content of each page',
			},
			{
				displayName: 'Scrape Timeout',
				name: 'scrapeTimeout',
				type: 'number',
				default: 30000,
				description: 'Timeout in milliseconds for scraping each page',
			},
			{
				displayName: 'Scrape Wait For',
				name: 'scrapeWaitFor',
				type: 'number',
				default: 0,
				description: 'Milliseconds to wait after page load before scraping',
			},
			{
				displayName: 'Sitemap',
				name: 'sitemap',
				type: 'options',
				options: [
					{ name: 'Auto', value: 'auto' },
					{ name: 'Force', value: 'force' },
					{ name: 'Skip', value: 'skip' },
				],
				default: 'auto',
				description: 'Whether to use the sitemap for URL discovery',
			},
			{
				displayName: 'Webhook Events',
				name: 'webhookEvents',
				type: 'multiOptions',
				options: [
					{ name: 'Completed', value: 'completed' },
					{ name: 'Failed', value: 'failed' },
					{ name: 'Page', value: 'page' },
				],
				default: [],
				description: 'Events to send to the webhook URL',
			},
			{
				displayName: 'Webhook URL',
				name: 'webhookUrl',
				type: 'string',
				default: '',
				placeholder: 'e.g. https://your-server.com/webhook',
				description: 'HTTPS URL to receive crawl event notifications',
			},
		],
	},
];
