import type { INodeProperties } from 'n8n-workflow';

export const searchFields: INodeProperties[] = [
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'e.g. web scraping best practices',
		description: 'The search query to execute',
		displayOptions: {
			show: {
				operation: ['search'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['search'],
			},
		},
		options: [
			{
				displayName: 'Categories',
				name: 'categories',
				type: 'multiOptions',
				options: [
					{ name: 'GitHub', value: 'github' },
					{ name: 'PDF', value: 'pdf' },
					{ name: 'Research', value: 'research' },
				],
				default: [],
				description: 'Filter results by category',
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
				placeholder: 'e.g. us, gb, de',
				description: 'Country code to localize search results',
			},
			{
				displayName: 'Language',
				name: 'lang',
				type: 'string',
				default: 'en',
				description: 'Language for search results',
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: {
					minValue: 1,
				},
				default: 50,
				description: 'Max number of results to return',
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'e.g. San Francisco',
				description: 'Location to localize search results',
			},
			{
				displayName: 'Scrape Exclude Tags',
				name: 'scrapeExcludeTags',
				type: 'string',
				default: '',
				placeholder: 'e.g. nav,footer,aside',
				description: 'Comma-separated HTML tags to exclude when scraping results',
			},
			{
				displayName: 'Scrape Formats',
				name: 'scrapeFormats',
				type: 'multiOptions',
				options: [
					{ name: 'HTML', value: 'html' },
					{ name: 'Links', value: 'links' },
					{ name: 'Markdown', value: 'markdown' },
					{ name: 'Screenshot', value: 'screenshot' },
				],
				default: [],
				description: 'Scrape each result page and return content in these formats',
			},
			{
				displayName: 'Scrape Include Tags',
				name: 'scrapeIncludeTags',
				type: 'string',
				default: '',
				placeholder: 'e.g. article,main,section',
				description: 'Comma-separated HTML tags to include when scraping results',
			},
			{
				displayName: 'Scrape Only Main Content',
				name: 'scrapeOnlyMainContent',
				type: 'boolean',
				default: false,
				description: 'Whether to extract only the main content when scraping results',
			},
			{
				displayName: 'Scrape Remove Base64 Images',
				name: 'scrapeRemoveBase64Images',
				type: 'boolean',
				default: false,
				description: 'Whether to remove base64-encoded images from scraped content',
			},
			{
				displayName: 'Scrape Strip Non-Content Tags',
				name: 'scrapeStripNonContentTags',
				type: 'boolean',
				default: false,
				description: 'Whether to strip non-content HTML tags from scraped results',
			},
			{
				displayName: 'Sources',
				name: 'sources',
				type: 'multiOptions',
				options: [
					{ name: 'Images', value: 'images' },
					{ name: 'News', value: 'news' },
					{ name: 'Web', value: 'web' },
				],
				default: ['web'],
				description: 'Types of search results to include',
			},
			{
				displayName: 'Time Filter',
				name: 'tbs',
				type: 'options',
				options: [
					{ name: 'Any Time', value: '' },
					{ name: 'Past Day', value: 'day' },
					{ name: 'Past Month', value: 'month' },
					{ name: 'Past Week', value: 'week' },
					{ name: 'Past Year', value: 'year' },
				],
				default: '',
				description: 'Filter results by time period',
			},
			{
				displayName: 'Timeout',
				name: 'timeout',
				type: 'number',
				default: 0,
				description: 'Request timeout in milliseconds',
			},
		],
	},
];
