import type { INodeProperties } from 'n8n-workflow';

export const pdfFields: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['pdf'],
			},
		},
		options: [
			{
				displayName: 'Add Script Tag',
				name: 'addScriptTag',
				type: 'json',
				default: '[]',
				placeholder: 'e.g. [{"url": "https://example.com/script.js"}]',
				description: 'JavaScript files or inline scripts to inject before PDF generation',
			},
			{
				displayName: 'Add Style Tag',
				name: 'addStyleTag',
				type: 'json',
				default: '[]',
				placeholder: 'e.g. [{"content": "body { font-size: 14px; }"}]',
				description: 'CSS files or inline styles to inject before PDF generation',
			},
			{
				displayName: 'Block Consent Modals',
				name: 'blockConsentModals',
				type: 'boolean',
				default: false,
				description: 'Whether to automatically block cookie consent modals',
			},
			{
				displayName: 'Display Header Footer',
				name: 'displayHeaderFooter',
				type: 'boolean',
				default: false,
				description: 'Whether to display a header and footer',
			},
			{
				displayName: 'Footer Template',
				name: 'footerTemplate',
				type: 'string',
				default: '',
				description: 'HTML template for the print footer',
			},
			{
				displayName: 'Format',
				name: 'format',
				type: 'options',
				options: [
					{ name: 'A0', value: 'A0' },
					{ name: 'A1', value: 'A1' },
					{ name: 'A2', value: 'A2' },
					{ name: 'A3', value: 'A3' },
					{ name: 'A4', value: 'A4' },
					{ name: 'A5', value: 'A5' },
					{ name: 'A6', value: 'A6' },
					{ name: 'Ledger', value: 'Ledger' },
					{ name: 'Legal', value: 'Legal' },
					{ name: 'Letter', value: 'Letter' },
					{ name: 'Tabloid', value: 'Tabloid' },
				],
				default: 'Letter',
				description: 'Paper format for the PDF',
			},
			{
				displayName: 'Full Page',
				name: 'fullPage',
				type: 'boolean',
				default: false,
				description: 'Whether to generate a single-page PDF of the full content',
			},
			{
				displayName: 'Header Template',
				name: 'headerTemplate',
				type: 'string',
				default: '',
				description: 'HTML template for the print header',
			},
			{
				displayName: 'Landscape',
				name: 'landscape',
				type: 'boolean',
				default: false,
				description: 'Whether to use landscape orientation',
			},
			{
				displayName: 'Margin Bottom',
				name: 'marginBottom',
				type: 'string',
				default: '',
				placeholder: 'e.g. 1cm, 0.5in',
				description: 'Bottom margin (CSS units)',
			},
			{
				displayName: 'Margin Left',
				name: 'marginLeft',
				type: 'string',
				default: '',
				placeholder: 'e.g. 1cm, 0.5in',
				description: 'Left margin (CSS units)',
			},
			{
				displayName: 'Margin Right',
				name: 'marginRight',
				type: 'string',
				default: '',
				placeholder: 'e.g. 1cm, 0.5in',
				description: 'Right margin (CSS units)',
			},
			{
				displayName: 'Margin Top',
				name: 'marginTop',
				type: 'string',
				default: '',
				placeholder: 'e.g. 1cm, 0.5in',
				description: 'Top margin (CSS units)',
			},
			{
				displayName: 'Omit Background',
				name: 'omitBackground',
				type: 'boolean',
				default: false,
				description: 'Whether to hide the default white background',
			},
			{
				displayName: 'Outline',
				name: 'outline',
				type: 'boolean',
				default: false,
				description: 'Whether to embed the document outline (bookmarks) in the PDF',
			},
			{
				displayName: 'Page Height',
				name: 'height',
				type: 'string',
				default: '',
				placeholder: 'e.g. 11in, 297mm',
				description: 'Custom page height (overrides format)',
			},
			{
				displayName: 'Page Ranges',
				name: 'pageRanges',
				type: 'string',
				default: '',
				placeholder: 'e.g. 1-5, 8, 11-13',
				description: 'Page ranges to include in the PDF',
			},
			{
				displayName: 'Page Width',
				name: 'width',
				type: 'string',
				default: '',
				placeholder: 'e.g. 8.5in, 210mm',
				description: 'Custom page width (overrides format)',
			},
			{
				displayName: 'Prefer CSS Page Size',
				name: 'preferCSSPageSize',
				type: 'boolean',
				default: false,
				description:
					'Whether to use the CSS-defined page size instead of the format option',
			},
			{
				displayName: 'Print Background',
				name: 'printBackground',
				type: 'boolean',
				default: false,
				description: 'Whether to print background graphics',
			},
			{
				displayName: 'Scale',
				name: 'scale',
				type: 'number',
				typeOptions: {
					minValue: 0.1,
					maxValue: 2,
				},
				default: 1,
				description: 'Scale of the webpage rendering (0.1 to 2)',
			},
			{
				displayName: 'Tagged',
				name: 'tagged',
				type: 'boolean',
				default: false,
				description: 'Whether to generate a tagged (accessible) PDF',
			},
			{
				displayName: 'Timeout',
				name: 'timeout',
				type: 'number',
				default: 0,
				description: 'PDF generation timeout in milliseconds',
			},
			{
				displayName: 'Wait For Fonts',
				name: 'waitForFonts',
				type: 'boolean',
				default: false,
				description: 'Whether to wait for all fonts to be loaded before generating',
			},
		],
	},
];
